version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/circleci-yxtg
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: node -v
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: echo '部署开始'
      - run : npm run build
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "13:88:ca:bf:5a:73:31:98:dc:b2:a4:c0:9b:f0:d0:8a"
      - run: echo StrictHostKeyChecking no \n echo UserKnownHostsFile /dev/null >> ~/.ssh/known_hosts
      - run: ls
      # - deploy:
      #     name: deploy
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" = "master" ]; then
      #         rsync -avce ssh build $SSH_USER@$SSH_IP:/root/yxtg
      #         npm 
      #       else
      #         echo "Not master branch, dry run only"
      #       fi
      # - run: echo '部署完毕'
