version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/circleci-yxtg
    filters:
      branches:
        only: master
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "21:4a:d0:4d:bd:ca:73:5f:00:fb:4d:15:2c:bb:bb:f2"
      - run: echo [$SSH_IP]:$SSH_PORT $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      # - run: ls && cat ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
               ssh -p $SSH_PORT $SSH_USER@$SSH_IP "cd /root/yxtg && git checkout master && git pull origin master &&npm install&& npm run build && pm2 update 0"
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕'
