version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/circleci-yxtg
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: tar -czvf dist.tar  dist .nuxt
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "21:4a:d0:4d:bd:ca:73:5f:00:fb:4d:15:2c:bb:bb:f2"
      - run: echo [$SSH_IP]:$SSH_PORT $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ssh -p $SSH_PORT $SSH_USER@$SSH_IP "rm -rf /root/yxtg/dist.tar" && rsync -avce "ssh -p $SSH_PORT" dist.tar $SSH_USER@$SSH_IP:/root/yxtg && ssh -p $SSH_PORT $SSH_USER@$SSH_IP "rm -rf /root/yxtg/dist /root/yxtg/.nuxt" && ssh -p $SSH_PORT $SSH_USER@$SSH_IP "cd /root/yxtg && tar -zxvf dist.tar && pm2 restart tfkz"
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕'
